%%
% Launch test_distmat_interpol in batch mode.

names_list = { ...
    {'centaur1' 'horse'}, ...
    {'centaur1' 'man1'}, ...
    {'man1' 'horse1'}, ...
    };
names_list = {...
    {'bird2' 'cat'}, ...
    {'chicken2' 'star8'}, ...
    {'dog' 'elephant'}, ...
    {'giraf' 'plane'}, ...
    {'star8' 'swan'}, ...
    {'cross' 'trefle'}, ...
    {'bird' 'camel'}, ...
    {'apple' 'star4'}, ...
    {'star5' 'heart2'}, ...
    {'chicken' 'device'}, ...
    {'disk' 'heart' }, ...
    {'thinspiral' 'triskel'}, ...
    {'rabbit' 'scissors1'}, ...
    {'horse' 'man'}, ...
    {'giraf' 'scissors2'}, ...
    {'man1' 'horse1'}, ...
    {'centaur1' 'horse1'}, ...
    {'centaur1' 'man1'}, ...
    {'chicken' 'device'}, ...
    };
% names_list = { {'centaur1' 'horse1'} };
% names_list = { {'chicken' 'device'} };


dist_mode_list = {'euclidean' 'geodesic'};
dist_mode_list = {'euclidean'};
dist_mode_list = {'geodesic'};

gw_loss_list = {'kl5' 'kl10' 'kl15' 'kl20' 'l2'};
gw_loss_list = {'kl8' 'kl10' 'kl15' 'l2'}; 
gw_loss_list = {'kl5' 'kl8' 'kl10' 'kl15' 'l2'};
gw_loss_list = {'l2'};

for it_name = 1:length(names_list)
    names = names_list{it_name};
    for it_loss = 1:length(gw_loss_list)
        gw_loss = gw_loss_list{it_loss};
        for it_mode=1:length(dist_mode_list)
            dist_mode = dist_mode_list{it_mode};
            fprintf('##### %s -- (%s,%s) #####\n', dist_mode, names{1}, names{2});
            test_distmat_interpol;
        end
    end
end

